kevm klab-*: fix prefix stripping, prompt before executing KLab

diff --git a/kevm b/kevm
--- a/kevm
+++ b/kevm
@@ -72,7 +72,7 @@ run_klab() {
     local run_mode
 
     run_mode="$1" ; shift
-    "$0" "$run_mode" --backend java "${run_file#$curdir}" \
+    "$0" "$run_mode" --backend java "${run_file#$curdir/}" \
         --state-log --state-log-path "$klab_dir/data" --state-log-id klab-statelog \
         --state-log-events OPEN,EXECINIT,SEARCHINIT,REACHINIT,REACHTARGET,REACHPROVED,NODE,RULE,SRULE,RULEATTEMPT,IMPLICATION,Z3QUERY,Z3RESULT,CLOSE \
         --output-flatten "_Map_ #And" \
@@ -82,6 +82,11 @@ run_klab() {
         --output json \
         "$@" \
         || true
+
+    echo
+    notif "Execute KLab? [y/n]"
+    read -n 1 -r
+    [[ "$REPLY" =~ ^[Yy]$ ]] || fatal "Aborting KLab run."
 
     export KLAB_OUT="$klab_dir"
     # klab often runs out of stack space when running long-running KEVM programs
