tangle: use bash's `set -e` to exit immediately on failure
This fixes `tangle all` running tests with an old compile output on
build failure.

We need to be a bit more careful when running commands that we exepect
to fail. Here the diff may fail, but we want to continue anyway, so we
must add the `||` branch.

diff --git a/tangle b/tangle
--- a/tangle
+++ b/tangle
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set -e      # Exit immediately if any command fails
+
 progress() { echo "==== $@"; }
 success()  { echo -e "\e[32m==== success: $@\e[0m"; }
 failure()  { echo -e "\e[31m==== failure: $@\e[0m"; }
@@ -52,20 +54,21 @@ tangle_test() {
     progress "Running tests"
     output_file="tests/templates/output.txt"
 
-    result='0'
-    local test_file
+    local test_file test_fail_count=0
     list_tests "$@" |
     while read test_file; do
+        local output_differs=false
         progress "running: $test_file..."
-        diff <(krun --debug --directory k/ "$test_file") "$output_file"
-        if [[ "$?" == '0' ]]; then
-            success "$test_file"
-        else
+        diff <(krun --debug --directory k/ "$test_file") "$output_file" \
+            || output_differs=true
+        if $output_differs; then
             failure "$test_file"
-            result='1'
+            test_fail_count+=1
+        else
+            success "$test_file"
         fi
     done
-    exit "$result"
+    return $test_fail_count
 }
 
 tangle_ktest() {
